title: Manual de Usuario
theme: jekyll-theme-leap-day
author_name: Miguel Angel Robles R
twitter_username: miguelrsrn
github_username:  ma-robles
instagram_username: mi4rob
email: miguel.robles@atmosfera.unam.mx
#repo: https://github.com/ma-robles/template_manual/
lang: "es-mx"
show_downloads: true
downloads:
  pdf_url: http://example.com/download.pdf
